name: main
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  path: ^1.8.0
  threading: ^0.0.8
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0
